{"name": "Проверка ошибки создания существующего пользователя", "status": "passed", "start": 1740154076457, "stop": 1740154076682, "uuid": "35ea7c9b-1f85-431c-ba46-cd89db551f7c", "historyId": "259a2ca50a04fc7eb748164abef18dbe", "testCaseId": "259a2ca50a04fc7eb748164abef18dbe", "fullName": "tests.test_create_user.TestCreateUser#test_create_not_unique_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "GM0V7WMM2R-MBP"}, {"name": "thread", "value": "46293-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}